package io.github.guilhermebars.matchforge.engine;

public enum RejectionReason {
    INSUFFICIENT_FUNDS, UNKNOWN_SYMBOL, INVALID_TICK, INVALID_LOT, INVALID_QUANTITY,
    UNKNOWN_ACCOUNT, ACCOUNT_EXISTS, UNKNOWN_ORDER, NOT_ORDER_OWNER, INVALID_AMOUNT,
    INVALID_QUOTE_BUDGET, INVALID_ORDER, UNKNOWN_ASSET, NUMERIC_OVERFLOW, SELF_TRADE,
    DUPLICATE_CLIENT_ORDER_ID
}
